# Generated by Django 3.0.3 on 2020-03-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200308_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='anhao',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
