# Generated by Django 3.0.3 on 2020-03-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_userinfo_anhao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='media/avatars/default.png', upload_to='media/avatars/', verbose_name='头像'),
        ),
    ]
